CREATE DATABASE IF NOT EXISTS mini_fstore;

CREATE TABLE IF NOT EXISTS mini_fstore.file (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT "primary key",
  file_id VARCHAR(32) NOT NULL COMMENT 'file id',
  status VARCHAR(10) NOT NULL COMMENT 'status',
  size BIGINT NOT NULL COMMENT 'size in bytes',
  md5 VARCHAR(32) NOT NULL COMMENT 'md5',
  upl_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'upload time',
  del_time TIMESTAMP NULL DEFAULT NULL COMMENT 'delete time',
  UNIQUE KEY (file_id),
  KEY (md5)
) ENGINE=INNODB COMMENT 'File';
